### ISSUE TITLE
Store and Load instructions take in a constant offset

### ISSUE THREAD

**Issue by Mee42** [adrian154/tvm#10]
Many load/read operations in cpus happen from a given base plus a constant offset. Examples include (in x86)
- accessing variables and functions arguments that were passed on the stack .`[rsp - 16]`
- accessing the Nth (n is constant) value in an array `[arrayptr + N]`
- accessing a member in a struct, where it isn't the first element

Currently, in TVM, having a constant offset from a memory access requires a scratch register and an add instruction, or a scratch register + add + a subtract instruction after to set the value back. It works, but it isn't ideal, and having a constant offset would make this significantly better.

This would also remove the current existing because of setting the stack pointer to wherever you want to write/read from and then calling push/pop respectively to read or write many sequential bytes. Probably for the better.

The spec would be changed to this (or smth similar):

.|.|.|.
---|---|---|---
|`0x3`|STOREB|Source(Value), Source(Address), Source(Offset)|Stores lower byte of Value into memory at \[Address + Offset]|
|`0x4`|STOREW|Source(Value), Source(Address), Source(Offset)|Stores Value into memory at \[Address + Offset] and \[Address + 1]|
|`0x5`|LOADB|Source, Source(Offset), Register|Loads byte in memory at address \[Source + Offset] into Register|
|`0x6`|LOADW|Source, Source(Offset), Register|Loads word in memory at address \[Source + Offset] into Register|

**Comment by adrian154** [comment]
Implemented in 6be85e5. The new instructions do not match the ones suggested here to maximize compatibility while avoiding inconsistencies, check the updated docs for info on them.
