### ISSUE TITLE
When tmpprint'ing too many characters without a linebreak, the output window becomes the size of the entire web page

### ISSUE THREAD

**Issue by Mee42** [adrian154/tvm#2]
It should instead have a scrollbar on the bottom, and the size of the window should be adjustable (feature request??)

kinda odd to have the code just shoved to the side.

**Comment by Mee42** [comment]
I see now that <reset> will reset it to a reasonable state though, so it's not too breaking

**Comment by Mee42** [comment]
nevermind it completely breaks the output buffer when this happens, and <reset> doesn't fix it

**Comment by adrian154** [comment]
Confirmed :'(

**Comment by somebody1234** [comment]
smhsmh bug still here?

**Comment by adrian154** [comment]
it was fixed in 21058326c53d9c4822ef9b1b27c13a5a300e3da2 actually, thanks for mentioning it
