### ISSUE TITLE
Clicking "reset" after assembling seems to fill the outputted assembly with nops, or something of the sort

### ISSUE THREAD

**Issue by Mee42** [adrian154/tvm#3]
To duplicate: open a new tab, use code
```
tmpprint 0x2A
```
click <assemble and write>, then <run>, and it works

click <assembly and write>, then <reset>, then <run>, and it doesn't print anything

**Comment by adrian154** [comment]
Works as intended, reset is meant to clear all CPU state including registers and memory.

**Comment by Mee42** [comment]
ah okay, makes sense
