### ISSUE TITLE
negative numbers are not a thing

### ISSUE THREAD

**Issue by Mee42** [adrian154/tvm#4]

**Comment by adrian154** [comment]
Works as intended. Instructions for two's complement arithmetic are available, so signed arithmetic is possible as long as your code is aware of it

**Comment by Mee42** [comment]
Negative integer literals aren't properly lexed, so `pushw -1` doesn't parse, for example.

**Comment by adrian154** [comment]
oh shoot thats what you meant, you are right then, confirmed
