### ISSUE TITLE
Offensive Equal Sign in Code

### ISSUE THREAD

**Issue by warp-records** [adrian154/tvm#9]
In your code, there are many instances of triple equal signs, where you only need a double equal sign; This is very offensive, because you clearly don't take equality seriously! I can't believe with all of the womens', LGBTQ+, and people of colors' rights issues that you would blatantly throw this into your code. For example, in `char === "\n"`, you went out of your way to put three equal signs where it's not needed, yet you didn't even use single quotes for proper notation? I know it may seem like a bit of a stretch, but equal signs in programming reflect how you view equality as a socio-political matter as well. It's just like how the Linux project removed "slave" and "master" from their code, and replaced it with "worker" and "host", because they realized it was offensive. I think this is highly offensive, and you need to change all instances of triple equal signs to double equal signs immediately, or else you're racist, homophobic, sexist, and a total extreme right wing conservative xenophobic asshole.

**Comment by chfour** [comment]
please tell me this is a copypasta that rift only found

**Comment by adrian154** [comment]
looking back this is one of the worst things ive ever had the great displeasure of reading

**Comment by warp-records** [comment]
Me too lol, I mean who would write something like that!
